### ISSUE TITLE
多用户登录

### ISSUE THREAD

**Issue by fys666** [srcrs/UnicomTask#1]
你好，我想问一下如何实现多用户登陆？
 可否使用电话1空格电话2
 然后密码也是对应的电话1电话2？
谢谢，新年好

**Comment by srcrs** [comment]
@fys666 新年好，建议多用户用actions配置文件方式去实现
```yml
name: UnicomTask

on:
  push:
    branches: main
  gollum:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build and publish
      env:
        USERNAME_COVER: ${{ secrets.USERNAME_COVER }}
        PASSWORD_COVER: ${{ secrets.PASSWORD_COVER }}
        APPID_COVER: ${{secrets.APPID_COVER}}
        EMAIL_COVER: ${{secrets.EMAIL_COVER}}
        LOTTERY_NUM: ${{secrets.LOTTERY_NUM}}
      run: |
        python main.py
    #这部分便是第二个账号，只需要在secrets添加对应的账号信息即可
    - name: Build and publish 2
      env:
        USERNAME_COVER: ${{ secrets.USERNAME_COVER_2 }}
        PASSWORD_COVER: ${{ secrets.PASSWORD_COVER_2 }}
        APPID_COVER: ${{secrets.APPID_COVER_2}}
        EMAIL_COVER: ${{secrets.EMAIL_COVER_2}}
        LOTTERY_NUM: ${{secrets.LOTTERY_NUM_2}}
      run: |
        python main.py
```
